### ISSUE TITLE
Javascript errors in browser console when scrolling a page without stickyheader

### ISSUE THREAD

**Issue by dduers** [benjaminkott/bootstrap_package#838]
# Bug Report

## Prerequisites

* [ n/a ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ yes ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

When constant `page.theme.navigation.type` is set `Default` or `Fixed Bottom` lots of javascript errors appear in the browser console when scrolling the page in the frontend. The errors won't appear when `page.theme.navigation.type` is set `Fixed Top`

## Steps to Reproduce

1. Set constant `page.theme.navigation.type` to `Default` or `Fixed Bottom`
2. Clear caches
3. Refresh frontend and scroll the page, lots of javascript errors (`TypeError: Cannot read property 'classList' of undefined`)

### Screenshots

(Attached)

## Versions

bootstrap_package 11.0.2

![1](https://user-images.githubusercontent.com/44911486/71519342-74af6780-28b7-11ea-8f0d-5ad2fe9acd57.png)
![2](https://user-images.githubusercontent.com/44911486/71519353-80029300-28b7-11ea-8d84-87fe7edcd337.png)

**Comment by gilbertsoft** [comment]
Thanks for your report. This problem is already solved see https://github.com/benjaminkott/bootstrap_package/commit/631161b7bca1a72079a8563dab48f16d1bf0850a

#834

**Comment by spoonerWeb** [comment]
I get this bug with JS error `Uncaught TypeError: stickyheader[0] is undefined` on TYPO3 10.4.6 and BP 11.0.2.
It appears during scrolling on the website, FF and Chrome.

![Uncaught TypeError: stickyheader is undefined](https://user-images.githubusercontent.com/1793083/89821297-a6c3c000-db4e-11ea-9438-efdaac57cb26.jpg)

**Comment by Moongazer** [comment]
I can confirm this, in the current release (11.0.2) the patch [631161b](https://github.com/benjaminkott/bootstrap_package/commit/631161b7bca1a72079a8563dab48f16d1bf0850a) seems to be not applied.

The `bootstrap.stickyheader.js` still has the code without `if (stickyheader.length >= 1)` condition to test if the stickyheader is present.

**Comment by hirnsturm** [comment]
I confirm with @spoonerWeb and @Moongazer. This issue is still present in TYPO3 10.4.6 and BP 11.0.2.

**Comment by boneyfantaseas** [comment]
Please publish a new release which incorporates #834 ! It couldn't be included in 11.0.2 as it was solved a day after that release.
